<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>猫玖键映板</AssemblyName>
    <RootNamespace>Click2Key</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <ApplicationIcon>Assets\taskbar-enabled.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\catgirl-*.png" />
    <Resource Include="Assets\taskbar-*.ico" />
    <Resource Include="Assets\app-icon-title.png" />
    <Resource Include="Assets\taskbar-*.png" />
    <Resource Include="Assets\Fonts\*.otf" />
  </ItemGroup>
</Project>

